package com.line.onlineweb.dao.entity;

public class FootSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_site.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_site.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_site.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_site.match_name
     *
     * @mbggenerated
     */
    private String matchName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_site.id
     *
     * @return the value of foot_site.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_site.id
     *
     * @param id the value for foot_site.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_site.name
     *
     * @return the value of foot_site.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_site.name
     *
     * @param name the value for foot_site.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_site.start_time
     *
     * @return the value of foot_site.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_site.start_time
     *
     * @param startTime the value for foot_site.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_site.match_name
     *
     * @return the value of foot_site.match_name
     *
     * @mbggenerated
     */
    public String getMatchName() {
        return matchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_site.match_name
     *
     * @param matchName the value for foot_site.match_name
     *
     * @mbggenerated
     */
    public void setMatchName(String matchName) {
        this.matchName = matchName == null ? null : matchName.trim();
    }
}