package com.line.onlineweb.dao.entity;

import java.util.Date;

public class UserPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.site_id
     *
     * @mbggenerated
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.say_info
     *
     * @mbggenerated
     */
    private String sayInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.foot_result
     *
     * @mbggenerated
     */
    private String footResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.hot
     *
     * @mbggenerated
     */
    private Long hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.click
     *
     * @mbggenerated
     */
    private Long click;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.id
     *
     * @return the value of user_plan.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.id
     *
     * @param id the value for user_plan.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.user_id
     *
     * @return the value of user_plan.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.user_id
     *
     * @param userId the value for user_plan.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.site_id
     *
     * @return the value of user_plan.site_id
     *
     * @mbggenerated
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.site_id
     *
     * @param siteId the value for user_plan.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.say_info
     *
     * @return the value of user_plan.say_info
     *
     * @mbggenerated
     */
    public String getSayInfo() {
        return sayInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.say_info
     *
     * @param sayInfo the value for user_plan.say_info
     *
     * @mbggenerated
     */
    public void setSayInfo(String sayInfo) {
        this.sayInfo = sayInfo == null ? null : sayInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.foot_result
     *
     * @return the value of user_plan.foot_result
     *
     * @mbggenerated
     */
    public String getFootResult() {
        return footResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.foot_result
     *
     * @param footResult the value for user_plan.foot_result
     *
     * @mbggenerated
     */
    public void setFootResult(String footResult) {
        this.footResult = footResult == null ? null : footResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.hot
     *
     * @return the value of user_plan.hot
     *
     * @mbggenerated
     */
    public Long getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.hot
     *
     * @param hot the value for user_plan.hot
     *
     * @mbggenerated
     */
    public void setHot(Long hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.click
     *
     * @return the value of user_plan.click
     *
     * @mbggenerated
     */
    public Long getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.click
     *
     * @param click the value for user_plan.click
     *
     * @mbggenerated
     */
    public void setClick(Long click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.create_time
     *
     * @return the value of user_plan.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.create_time
     *
     * @param createTime the value for user_plan.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}