package com.line.onlineweb.dao.entity;

import java.util.Date;

public class UserSupport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_support.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_support.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_support.plan_id
     *
     * @mbggenerated
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_support.support_type
     *
     * @mbggenerated
     */
    private String supportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_support.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_support.id
     *
     * @return the value of user_support.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_support.id
     *
     * @param id the value for user_support.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_support.user_id
     *
     * @return the value of user_support.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_support.user_id
     *
     * @param userId the value for user_support.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_support.plan_id
     *
     * @return the value of user_support.plan_id
     *
     * @mbggenerated
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_support.plan_id
     *
     * @param planId the value for user_support.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_support.support_type
     *
     * @return the value of user_support.support_type
     *
     * @mbggenerated
     */
    public String getSupportType() {
        return supportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_support.support_type
     *
     * @param supportType the value for user_support.support_type
     *
     * @mbggenerated
     */
    public void setSupportType(String supportType) {
        this.supportType = supportType == null ? null : supportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_support.create_time
     *
     * @return the value of user_support.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_support.create_time
     *
     * @param createTime the value for user_support.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}