package com.line.onlineweb.dao.mapper;

import com.line.onlineweb.dao.entity.FootSite;

public interface FootSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    int insert(FootSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    int insertSelective(FootSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    FootSite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FootSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_site
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FootSite record);
}