package com.line.onlineweb.dao.mapper;

import com.line.onlineweb.dao.entity.PayInfo;
import com.line.onlineweb.dao.entity.PayInfoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int countByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int deleteByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    List<PayInfo> selectByExampleWithRowbounds(PayInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    List<PayInfo> selectByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    PayInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") PayInfo record, @Param("example") PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int updateByExample(@Param("record") PayInfo record, @Param("example") PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Wed Aug 22 10:02:39 CST 2018
     */
    int updateByPrimaryKey(PayInfo record);
}