package com.line.onlineweb.dao.mapper;

import com.line.onlineweb.dao.entity.UserSupport;

public interface UserSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    int insert(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    int insertSelective(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    UserSupport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSupport record);

    UserSupport findByPlanId(Long id);

    UserSupport findByPlanIdAndUserId(Long planId, Long userId);
}