package com.line.onlineweb.dao.mapper;

import com.line.onlineweb.dao.entity.UserPlan;
import com.line.onlineweb.service.dto.FootShowDTO;

import java.util.List;
import java.util.Map;

public interface UserPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    int insert(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    int insertSelective(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    UserPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPlan record);

    List<FootShowDTO> findBySeachMap(Map<String, Object> map);
}